### ISSUE TITLE
feat(Header): setup

### ISSUE THREAD

**Issue by MetaMatt1** [MetaTech-dev/todo-client#9]
### tasks
- [x] create a folder `src/Layout`, move the Layout.js into that folder, and in that folder also create an index.js where you import the Layout.js and export it as default
- [x] create a component `src/Layout/Header.js` and add an mui AppBar that is statically positioned and has flexShrink so it will always be at the top of the app
- [x] create a menu icon button that does nothing when clicked for now
- [x] create a title for the app 'todo'
- [x] create a login button that is justified right and does nothing when clicked for now
- [x] import and put the Header into the Layout component inside the container box above the Outlet

### resources
- https://mui.com/material-ui/react-app-bar/#basic-app-bar
